### Create an ndarray

In [1]:
import numpy as np

np.array(['a', 'b'])

array(['a', 'b'], dtype='<U1')

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.full(3, 2.71)

array([2.71, 2.71, 2.71])

In [4]:
np.arange(0, 10, 2) # 2-spaced values over [0, 10)

array([0, 2, 4, 6, 8])

In [5]:
A = np.arange(6)
A.shape

(6,)

In [6]:
A.reshape((-1, 2)) # '-1' requests #rows to be inferred

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
a = np.arange(3) # show with a = [0, 1, 2] at pythontutor.com|
copy = a.copy()
copy[0] = 10 # does not change a
view = a
view[1] = 11 # changes a
print(f'a={a}, copy={copy}, view={view}')

a=[ 0 11  2], copy=[10  1  2], view=[ 0 11  2]


### Array types (dtype)

In [ ]:
np.array([1, 2, 3])

In [ ]:
A = np.array([1, np.sqrt(2), np.e, np.pi])
A

In [ ]:
1 < A

In [ ]:
np.sum(1 < A)

In [ ]:
np.array(['apple', 'banana', 'cherry'])

### A few functions

In [ ]:
np.amax(A)

In [ ]:
np.argmax(A)

In [ ]:
x = 1 + np.arange(5)
print(x)
np.std(x, ddof=1) 

In [ ]:
B = np.array([13, 10, 12, 11])
B

In [ ]:
np.sort(B)

In [ ]:
np.argsort(B)

In [ ]:
B[np.argsort(B)]

In [ ]:
np.flip(np.sort(B)) # np.flip() reverses an array

In [ ]:
price = np.array((10, 15, 12)) # use np.argsort() to sort two parallel arrays
n_shares = np.array((1, 2, 5)) # while keeping them parallel
indicesToSortPrice = np.argsort(price)
indicesToSortPrice

In [ ]:
price[indicesToSortPrice]

In [ ]:
n_shares[indicesToSortPrice]

In [ ]:
np.isin(np.array([1, 2, 3]), np.array([2, 7]))

### Aside: What's the difference between [], (), and {}?
[] enclose a list; and [] are for indexing into a sequence (string, tuple, list) or array,
e.g. price[2]

() enclose a tuple; and () enclose the arguments to a function,
e.g. np.sort(price)

We have used {} only in a print(f'...') statement to say,
"give the value of the enclosed variable," e.g
print(f'x={x}')

### Operators (which act element-wise)

In [9]:
x = 1 + np.arange(5)
x

array([1, 2, 3, 4, 5])

In [10]:
n = len(x)
np.sqrt(np.sum((x - np.mean(x))**2) / (n - 1)) # no loop; inspect parts

1.5811388300841898

In [11]:
# We could not do this with a list--thus the Q03 exercises
# to find std(x), where x was a list, required a loop. NumPy was
# written to make this kind of computation easier, faster, and
# less memory-intensive.
y = [1, 2, 3]
# y - 2 # uncomment to see error: can't do this with a list (without a loop)

In [19]:
A

array([0, 1, 2, 3, 4, 5])

In [13]:
1 < A

array([False, False,  True,  True,  True,  True])

In [14]:
A < 3

array([ True,  True,  True, False, False, False])

In [15]:
(1 < A) & (A < 3)

array([False, False,  True, False, False, False])

In [16]:
(1 < A) | (A < 3)

array([ True,  True,  True,  True,  True,  True])

In [17]:
(1 < A) ^ (A < 3)

array([ True,  True, False,  True,  True,  True])

In [18]:
~(1 < A)

array([ True,  True, False, False, False, False])

### Indexing

In [20]:
A[0]

0

In [21]:
A[3]

3

In [22]:
A[-1]

5

In [23]:
A[0:2]

array([0, 1])

In [24]:
A[:2]

array([0, 1])

In [25]:
A[0:]

array([0, 1, 2, 3, 4, 5])

In [26]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
a = np.array([0, 9])
a

array([0, 9])

In [28]:
x[a]

array([10, 19])

In [29]:
x[np.array([0, -1])]

array([10, 19])

In [30]:
A

array([0, 1, 2, 3, 4, 5])

In [31]:
indices = np.nonzero(1 < A)
indices

(array([2, 3, 4, 5], dtype=int64),)

In [32]:
A[indices]

array([2, 3, 4, 5])

In [33]:
A[1 < A]

array([2, 3, 4, 5])

In [34]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
x % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [36]:
(x % 2) == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [37]:
x[(x % 2) == 0]

array([10, 12, 14, 16, 18])

In [38]:
np.all(1 < A)

False

In [39]:
np.any(1 < A)

True

### Loop through values or indices, as with sequences

In [ ]:
for value in x:
    print(f'  value={value}')

In [ ]:
for i in np.arange(len(x)):
    print(f'  i={i}, x[{i}]={x[i]}')

### File input/output

In [ ]:
np.savetxt('A.txt', A)

In [ ]:
C = np.loadtxt('A.txt', float)
C