In [1]:
import numpy as np

In [2]:
A = np.array([4, 1, 3, 2])
A

array([4, 1, 3, 2])

In [3]:
A = np.arange(0, 100, 10)
A

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
# 3. Write a line of code that sets a variable A to an ndarray of 11 evenly-spaced numbers spanning [0, 1]. (hint)
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [5]:
# 4. Study the "Array types (dtype)" section of the notes.

# I have an array A of int. Write a line of code that sets array B to be a corresponding array of bool such that
# B[i] indicates whether A[i] is negative. For example, for A = np.array([3, -2, 4]),
# B should be np.array([False, True, False]).

A = np.array([3, -2, 4])
B = A < 0
B

array([False,  True, False])

In [6]:
# 5. Study the "A few functions" section of the notes.

# Consider the array 
# data = np.array([36,55,9,72,77,7,57,41,74,34,73,3,31,28,85,67,65,14,19,20,11,97,1,8,35,81,12,10,54,4]). 
# Find the smallest value.

data = np.array([45,94,82,80,77,33,53,73,81,13,67,78,16,30,84,32,42,86,18,72,9,47,1,26,76,5,46,93,27,52])
np.min(data)

1

In [7]:
# 6. Find the index of data's smallest value.
np.argmin(data)

22

In [8]:
# 7. Make a sorted copy of data (from largest to smallest). What is the largest number?
np.sort(data)[::-1]

array([94, 93, 86, 84, 82, 81, 80, 78, 77, 76, 73, 72, 67, 53, 52, 47, 46,
       45, 42, 33, 32, 30, 27, 26, 18, 16, 13,  9,  5,  1])

In [9]:
# 8. Find the sum of the 4 lowest values in data. (hint
sum(np.sort(data)[:4])

28

In [10]:
# 9. Find the sum of the indices of the 4 smallest elements of data. (hint)
sum(np.argpartition(data, 4)[:4])

76

In [11]:
# 10. Given this array of student names and corresponding exam scores,
# student = np.array(['Alex','Betty','Chen','David','Eleanor'])
# score = np.array([88,93,76,91,80])
# sort the names and the scores, each in decreasing order of scores. 
# Which student has the highest score? 
# (Encode your answer as a number via 1=Alex, 2=Betty, 3=Chen, 4=David, 5=Eleanor.) (hint)


In [12]:
# 11. Find the sum of values in data that are also in the array 
# subset = np.array([41,0,46,86,12,26,17,95,5,81,25,2,20,33,33]. (hint)
subset = np.array([41,0,46,86,12,26,17,95,5,81,25,2,20,33,33])

common_values = data[np.isin(data, subset)]

# Summing the common values
sum_of_common_values = np.sum(common_values)
sum_of_common_values

277

In [13]:
# 12. Study the "Operators" section of the notes.

# Given an array x of x coordinates, and an array y of y coordinates, an intercept a and a slope b, 
# write a line of code to set a variable SSE to the sum of squared errors for the pairs {(xi,yi)}
#  with respect to the line y=a+bx
# . That is, find SSE=∑e2i=∑(yi−yi^)2=∑(yi−a−bxi)2
# .
# For example, for x = np.array([0, 1, 2]); y = np.array([1, 3, 2]);
# a = 1.5; b = 0.5, SSE should be 1.5. It is the sum of squared (vertical) errors for the 
# three points (0, 1), (1, 3), (2, 2) with respect to the line y = 1.5 + 0.5x. 
# Drawing a picture of these points and this line may be helpful. (hint)

x = np.array([0, 1, 2])
y = np.array([1, 3, 2])
a = 1.5
b = 0.5

# Calculating the sum of squared errors (SSE)
SSE = np.sum((y - (a + b * x)) ** 2)
SSE


1.5

In [14]:
# 13. Study the "Indexing" section of the notes.

# Find the sum of values in data with even indices. (hint)

sum(data[::2])

724

In [15]:
# 14. Find the sum of the even values in data. (hint)
sum(data[data%2 == 0])

914

In [16]:
# 15. Find the sum of the values in data between 10 and 20, inclusive.

sum(data[(data >= 10) & (data <= 20)])

47

In [23]:
# 16. Study the "File input/output" section of the notes.

# Use np.loadtxt() to read the file Hamlet.txt into an array of strings.
# Find the number of times the word "memory" occurs. 
# (Don't count variations like "Memory" or answer should be a number, not Python code.) (hint)
# data = np.loadtxt('Hamlet.txt', dtype=str, delimiter='\n')

# Reading the text file line by line and storing it in a list
# with open('Hamlet.txt', 'r', encoding='utf-8') as file:
#     lines = file.readlines()

# # Converting the list of lines to a NumPy array
# data = np.array(lines)
# print(data)

# Reading the text file and counting the occurrences of the word "revenge"
with open('Hamlet.txt', 'r', encoding='utf-8') as file:
    text_content = file.read()

# Converting the text to lowercase to ensure case-insensitive matching
# text_content = text_content.lower()

# Counting the number of occurrences of the word "revenge"
count_revenge = text_content.split().count('revenge')
print(count_revenge)



2
